{"timestamp":"2025-07-15T02:39:09.343533","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-15T02:39:09.346513","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/DAG102.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-15T02:39:09.428471Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-15T02:39:09.429158Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-15T02:39:09.429972Z","level":"info","event":"Current task name:load_genres_to_postgres","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-15T02:39:09.430551Z","level":"info","event":"Dag name:movie_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-15T02:39:09.429048","level":"info","event":"Connection Retrieved 'postgres_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-15T02:39:09.479689","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"(psycopg2.OperationalError) connection to server at \"postgresmovie-postgres\" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\n\n(Background on this error at: https://sqlalche.me/e/14/e3q8)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/DAG102.py","lineno":134,"name":"load_genres_to_postgres"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/schema.py","lineno":4842,"name":"reflect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/inspection.py","lineno":64,"name":"inspect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py","lineno":182,"name":"_engine_insp"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py","lineno":117,"name":"_construct"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py","lineno":128,"name":"_init_engine"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":96,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3404,"name":"raw_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3374,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2208,"name":"_handle_dbapi_exception_noconnection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3371,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":327,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":894,"name":"_checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":493,"name":"checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":145,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":143,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":273,"name":"_create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":388,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":690,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":686,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py","lineno":574,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":598,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]},{"exc_type":"OperationalError","exc_value":"connection to server at \"postgresmovie-postgres\" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":3371,"name":"_wrap_pool_connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":327,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":894,"name":"_checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":493,"name":"checkout"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":145,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py","lineno":143,"name":"_do_get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":273,"name":"_create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":388,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":690,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py","lineno":70,"name":"__exit__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py","lineno":686,"name":"__connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py","lineno":574,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":598,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-15T02:39:09.530302Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-15T02:39:09.531001Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-15T02:39:09.531483Z","level":"info","event":"Task:<Task(PythonOperator): load_genres_to_postgres>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-15T02:39:09.532000Z","level":"info","event":"Failure caused by (psycopg2.OperationalError) connection to server at \"postgresmovie-postgres\" (172.18.0.3), port 5432 failed: FATAL:  password authentication failed for user \"postgres\"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-15T02:39:09.532458Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-15T02:39:09.532912Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/e3q8)","chan":"stdout","logger":"task"}
